site_name: CAKEbox
repo_url: https://github.com/CAKE-DRI/CAKEbox
repo_name: CAKE-DRI/CAKEbox
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/font-awesome
      link: https://cake-dri.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/CAKE-DRI
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/cake-dri/shared_invite/zt-3b6dgtkfp-kDnlCOXOl9QJrg0L7tVKNw

nav:
  - Welcome and Explore: index.md
  - How to Contribute: how-to-contribute/index.md

theme:
  name: material
  palette: 
    # scheme: default
    # primary: custom
 # Palette toggle for light mode
  - scheme: default
    primary: custom 
    toggle:
      icon: material/weather-sunny 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate 
    primary: custom 
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  font: 
    text: Ubuntu
  favicon: images/favicon.ico
  logo: images/CAKE_logo1_wht.png
  
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.action.edit
    - tags

extra_css:
  - stylesheets/cake.css
    
plugins:
  - search
  # - git-revision-date
  - meta
  - tags

  # - git-revision-date-localized
  # - git-committers
  # - git-revision-date-localized:
  #   enable_creation_date: true
  #   type: date
  
  # - git-committers:
  #   repository: CAKE-DRI/CAKEbox
  #   branch: main
    # tags_file: tags.md

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
